# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180216_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Метку', 'verbose_name_plural': 'Метки'},
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.Tag', verbose_name='Метки'),
        ),
    ]
