# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180328_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_date'], 'verbose_name': 'Метку', 'verbose_name_plural': 'Метки'},
        ),
    ]
