# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import landing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('custom_style', models.CharField(help_text='В этом поле вы можете задать css для изображения', max_length=300, verbose_name='Стили')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('source', models.FileField(upload_to=landing.models.UploadImageForGallery, verbose_name='Изображение')),
                ('identifier', models.CharField(max_length=100, verbose_name='Идентификатор группы')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Изображение',
                'ordering': ['-created_date'],
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя блока')),
                ('identifier', models.CharField(max_length=100, verbose_name='Идентификатор блока')),
                ('content', models.TextField(help_text='Если в блоке нужен простой текст, используйте это поле', verbose_name='Контент блока')),
                ('extend_content', models.TextField(verbose_name='Расширенный редактор блока')),
                ('is_extend', models.BooleanField(default=0, verbose_name='Выводить контент из расширенного редактора')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Блок текста',
                'ordering': ['-created_date'],
                'verbose_name_plural': 'Блоки текста',
            },
        ),
    ]
