# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20180627_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='href',
            field=models.CharField(blank=True, help_text='Если это предусмотрено шаблоном, при клике на картинку произойдет переход по заданной ссылке', max_length=500, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='custom_style',
            field=models.CharField(blank=True, help_text='В этом поле вы можете задать css для изображения, если это предусмотрено данной группой изображений', max_length=300, null=True, verbose_name='Стили'),
        ),
    ]
