# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('ceo_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категорию',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Новости')),
                ('content', models.TextField(verbose_name='Контент')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка')),
                ('published', models.BooleanField(default=1, verbose_name='Опубликована')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
                'verbose_name': 'Услуга',
            },
        ),
    ]
