# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20180404_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=service.models.UploadImageForServiceCategory, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ceo_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
