# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20180406_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Тип услуги', 'verbose_name_plural': 'Типы услуг'},
        ),
    ]
