# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 16:34
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('url', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published', models.BooleanField(default=1, verbose_name='Опубликовано')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.FileField(blank=True, null=True, upload_to=catalog.models.UploadImageForDetail, verbose_name='Изображение')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка')),
                ('published', models.BooleanField(default=1, verbose_name='Опубликовано')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.FileField(blank=True, null=True, upload_to=catalog.models.UploadImageForItem, verbose_name='Изображение')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка')),
                ('published', models.BooleanField(default=1, verbose_name='Опубликовано')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AddField(
            model_name='detail',
            name='items',
            field=models.ManyToManyField(to='catalog.Item', verbose_name='Изделия'),
        ),
    ]
