# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
