# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180104_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='published',
            field=models.BooleanField(default=1, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания'),
        ),
    ]
