# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180131_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='url',
        ),
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=1, help_text='Если категория не опубликована, она и всё обородование, принадлжащее этой категории, не будут доступны в каталоге', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, help_text='По ссылке будет доступно оборудование из данной категории. Если оставить поле пустым, ссылка автоматически сгенерируется из наименования.', max_length=200, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='items',
            field=models.ManyToManyField(help_text='Укажите для какого оборудование подойдет данная деталь.', to='catalog.Item', verbose_name='Изделия'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='published',
            field=models.BooleanField(default=1, help_text='Если деталь не опубликована, она не будет отображаться в каталоге', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='title',
            field=models.CharField(help_text='Название или маркировка запчасти', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Укажите категорию оборудования для удобной фильтрации', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='published',
            field=models.BooleanField(default=1, help_text='Если оборудование не опубликовано, оно не будет отображаться в каталоге', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(help_text='Название или модель оборудования', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(blank=True, help_text='Если оставить поле пустым, ссылка сгенерируется автоматическ из наименования', max_length=200, null=True, verbose_name='Ссылка'),
        ),
    ]
