# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180105_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('published', models.BooleanField(default=1, verbose_name='Опубликовано')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name_plural': 'Запчасти',
                'verbose_name': 'Запчасть',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=1, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='detail',
            name='items',
            field=models.ManyToManyField(to='catalog.Item', verbose_name='Продукция'),
        ),
    ]
