# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180203_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='description',
        ),
    ]
