# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 17:05
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180105_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=catalog.models.UploadImageForDetail, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='detail',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='items',
            field=models.ManyToManyField(to='catalog.Item', verbose_name='Изделия'),
        ),
    ]
