# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='topic',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Тема'),
        ),
    ]
