# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180518_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Примечание'),
        ),
    ]
