# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180521_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Категория'),
        ),
    ]
