# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_date_format',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время отправки'),
        ),
    ]
